# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          experimental: false
        - os: ubuntu-18.04
          experimental: false
        - os: ubuntu-16.04
          experimental: false
        - os: macos-11.0
          experimental: true
        - os: macos-10.15
          experimental: true
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Print Bash version
      run: bash --version

    - name: Install bc, haveged
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get --no-install-recommends install -y bc haveged

    - name: Foo
      run: tr -dc "0-9" < /dev/urandom | head -c 12

    - name: Test bash-funk
      shell: bash
      run: |
        export TERM=xterm
        source bash-funk.sh
        -test-all
